version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"     # Porta para conexões AMQP (pika)
      - "15672:15672"   # Painel de administração web
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
  
  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    container_name: api
    ports:
      - "80:8085"
    depends_on:
      - rabbitmq